### ISSUE TITLE
JsonParser silently ignores additional characters at the end of an input

### ISSUE THREAD

**Issue by Joe-Edwards** [spray/spray-json#137]
When trying to parse an input the JSON parser silently ignores anything at the end of the input. e.g.

```
val jsonString = """{ "json": "object" } and some extra characters"""

val jsValue = JsObject("json" -> JsString("object"))

JsonParser(ParserInput(jsonString)) == jsValue
```

returns true, whereas I'd expect to see some kind of exception. I'm using this in conjunction with akka-http SprayJsonSupport and I want to ensure clients don't try to send other data after the JSON.

Could we simply add a check onto the end of the 'parseJsValue' method to ensure we hit the EOI character?

**Comment by sirthias** [comment]
Yes, I think this is a valid request.
Thanks for reporting!

**Comment by pasieronen** [comment]
I'm using JsonParser.parseJsValue() to parse multiple values, and this change in spray-json 1.3.2 broke my code. Requiring end-of-input sounds like a reasonable default, though. Pull request #168 adds "requireEndOfInput" flag to re-enable pre-1.3.2 behavior.
