### ISSUE TITLE
Streaming in spray-json

### ISSUE THREAD

**Issue by jkinkead** [spray/spray-json#144]
I've started running into issues with spray-json scaling to larger data structures, and have hacked up a mostly-complete version of spray-json that supports streaming -

Branch: https://github.com/jkinkead/spray-json/tree/streaming

Compare link: https://github.com/spray/spray-json/compare/master...jkinkead:streaming

I say "version of spray-json", but it's very nearly standalone - it's leveraging a ton of the existing code, but only in the parser & writer internals. As you'd probably guess, it doesn't construct an AST representation going either direction, and therefore isn't directly compatible with spray-json's JsonFormats, although a streaming format would be possible for JsValue . . . but it would kind of defeat the point. :)

Is there any interest in adding this as a part of the spray-json project, either as a sub-package (like I currently have it set up) or as a sister library (maybe an sbt subproject)? I'll likely be publishing it for use on work projects soon, but it would be cool if it were rolled up into the main spray-json project.

Mostly I'm looking for a direction to take my final cleanup and documentation - if I should attempt to get this into a clean pull request, or if I should make it fully standalone as a new project.

**Comment by jkinkead** [comment]
I went ahead and made this standalone: https://github.com/jkinkead/reming-json

Let me know if you have any interest in trying to merge or anything!

**Comment by sirthias** [comment]
Thanks for the pointer, @jkinkead!
We have no capacity for major spray-json work at this point, but might want to come back to your code later...
