### ISSUE TITLE
Generating JSON Schema from Scala Case Classes

### ISSUE THREAD

**Issue by tobiasschweizer** [spray/spray-json#146]
Hi,

we are using spray-json to implement a RESTful API that generates JSON response formats (it works really well :-) ).

Since the JSON format is defined by case classes, we would like to generate JSON schema for documentation purposes. Is there a way to generate JSON Schema taking the scala case classes as input (something like scaladoc)?

The same questionwas asked quite some time ago: 
<http://stackoverflow.com/questions/16779883/is-there-a-way-to-get-a-json-schema-from-a-scala-case-class-hierarchy>

Thanks

Tobias

**Comment by sirthias** [comment]
Currently spray-json doesn't offer any such capability, sorry.
If you find something that might be interesting to the community you'd be very welcome if you report it on the [spray mailing list](https://groups.google.com/forum/#!forum/spray-user) though.
