### ISSUE TITLE
Why spray-json?

### ISSUE THREAD

**Issue by nlw0** [spray/spray-json#150]
Hi, not meaning to be rude, just really looking for information.

What is the objective of this project? With 5+ JSON libraries for Scala, it can be pretty confusing for new programmers to make a choice. I spent some time making [my own tests](https://github.com/nlw0/scala-json-benchmark), but I am still undecided. So I wanted to hear the opinions from people closer to the projects, as I feel we are mostly hearing superficial and outdated opinions from confused users out there on the web.

I like Spray/akka-http a lot, and I intend to use it in my projects. That makes me think I should maybe try to stick to spray-json. But at the same time, it seems all libraries are very similar and interchangeable, and there is even support for json4s in Spray. Also issue [#59](https://github.com/spray/spray-json/issues/59) kind of puts me away, even if it looks like a small thing. If it gets solved, I will only get more confused!

I have some applications where I need to use JSON that are not even web-related. When we remove the link to a web framework, it gets even harder to decide.

So I wanted to ask, what good reasons are there for us to pick this library instead of others? What kinds of features are planned? Is there at least a chance we might see spray-json merge with play-json, and lift-json with json4s, so we start having less options? What are your plans for this project?

**Comment by sirthias** [comment]
Discussed on the [mailing list](https://groups.google.com/d/msg/spray-user/OpS34RJEOuU/UybEhpEfTqsJ).
