### ISSUE TITLE
optionFormat and eitherFormat should be typed JsonFormat[T]

### ISSUE THREAD

**Issue by fommil** [spray/spray-json#151]
unfortunately these two implicit methods return very specific types, making them very troublesome to deal with when overriding or doing anything funky with shapless to automatically derive product/trait types.

**Comment by fommil** [comment]
actually, either might be ok. It's just `optionFormat` that's killing me.

**Comment by fommil** [comment]
I can workaround this with a non-implicit method of the same name, and introducing an implicit one with the correct return type.

**Comment by jkinkead** [comment]
This fix broke compatibility with version `1.3.1` - `optionFormat` has a different return type from `1.3.1`, and anything compiled against it will now throw a runtime exception like:
```
Exception in thread "main" java.lang.NoSuchMethodError: spray.json.DefaultJsonProtocol$.optionFormat(Lspray/json/JsonFormat;)Lspray/json/StandardFormats$OptionFormat;
```
I'll open a separate issue.

**Comment by fommil** [comment]
ouch

**Comment by fommil** [comment]
the workaround is to create an implicit override def that will return the specialised type instead of `JsonFormat[Option[T]]`
