### ISSUE TITLE
Decoding of 4-byte UTF-8 characters is not supported in JsonParser

### ISSUE THREAD

**Issue by markhatton** [spray/spray-json#156]
Decoding of 4-byte UTF-8 characters, including Emoji, is not supported.  Such characters resolve to the replacement character "�" (U+FFFD).

**Comment by jrudolph** [comment]
What? Smilies are broken in spray-json? This must be the saddest bug report ever. ☹

Thanks for taking care of it ☻☺☻

**Comment by sirthias** [comment]
Yes, surrogate pairs are currently not supported.
It shouldn't be hard however, to get this done.

**Comment by everpeace** [comment]
@sirthias When would we expect that this feature will be released?  

In product perspective, I recognize that current spray-json version is `1.3.2` but other spray components' are all `1.3.3`.  And the previous release of spray-json happened at the this May. Therefore I'm expecting spray-json `1.3.3` will be released soon.  Am I right?  Moreover, we're using spray-json in our next generation production system and we need this feature.

I hope this feature will be shipped soon.  I'm looking forward to hearing your response.

**Comment by everpeace** [comment]
@sirthias sorry for bothering you.  I'm really appreciated if you would reply about when next release happens.  Thanks,

**Comment by sirthias** [comment]
@everpeace The fix for this issue is already in the master branch, however, there are currently no plans for an immediate release. You should be able to use a local snapshot if you really depend on this feature.

**Comment by everpeace** [comment]
@sirthias Thank you for response!  I see I have to use snapshot version.  I hope next release will happen soon anyway.
