### ISSUE TITLE
Possible problem with parsing from Array[Byte] with Utf8 chars

### ISSUE THREAD

**Issue by ktoso** [spray/spray-json#162]
As seen in https://github.com/akka/akka/issues/18389

The string:

```
{"title":"ÇatÇat Kitapları","parentName":"Çocuk Kitapları"}
```

Unmarshalled incorrectly when parsed from byte array, but correctly when string was given.

**Comment by jrudolph** [comment]
This is most likely a duplicate of #148. Closing for now...
