### ISSUE TITLE
Invalid JSON is successfully parsed

### ISSUE THREAD

**Issue by theon** [spray/spray-json#167]
The following invalid JSON gets successfully parsed by ignoring the invalid trailing content. Is this expected? I feel like this should fail, or at least fail when a strict mode is enabled.

```scala
scala> import spray.json._
import spray.json._

scala> """ ["a"],["b"] """.parseJson
res0: spray.json.JsValue = ["a"]

```

**Comment by sirthias** [comment]
Yes, thanks for reporting!

**Comment by sirthias** [comment]
One question: it seems that this might be a duplicate of #137, which was already fixed.
Could you verify?

**Comment by theon** [comment]
Ah yes. Sorry missed that one!
