### ISSUE TITLE
Push build for 2.12.0-M4 into Sonatype

### ISSUE THREAD

**Issue by cppexpert** [spray/spray-json#188]
Hi guys!

Could you please push build for 2.12.0-M4 into Sonatype repo ?

Thanks!

**Comment by ktoso** [comment]
would be nice, though now for M5: https://github.com/spray/spray-json/issues/190

**Comment by sirthias** [comment]
1.3.2 is now published for 2.12.0-M5.
Sorry for not reacting further to this ticket!
I somehow missed it completely.
