### ISSUE TITLE
Publish for Scala 2.12.0-M5

### ISSUE THREAD

**Issue by ktoso** [spray/spray-json#190]
Hey @sirthias,
would you be able to publish for M5?
We're trying to make sure Akka HTTP is happy on latest milestone.

Relates, would you consider adding someone with publish rights (I'd be able to do that)?
I guess this will become less painful once 12 stable is out, but there's some M and RC still ahead of us

**Comment by ktoso** [comment]
Oh, I guess perhaps @jrudolph is able to publish spray things... that would solve it for us I guess :)

**Comment by sirthias** [comment]
Ok, just pushed `spray-json_2.12.0-M5-1.3.2` to sonatype.
Should be on maven central in half an hour or so.

**Comment by ktoso** [comment]
Great, thanks :)


On 7 July 2016 at 11:03:39, Mathias (notifications@github.com) wrote:

Closed #190.

**Comment by ktoso** [comment]
Great, thanks!
