### ISSUE TITLE
Release 1.3.2 for Scala 2.12.0-RC2

### ISSUE THREAD

**Issue by ktoso** [spray/spray-json#201]
Was blocking Akka HTTP so I'll release it.
I see you did some work for this @sirthias thanks!

I'll release the exact 1.3.2 for Scala 2.12.0-RC2 now.
I guess spray-json deserves a 1.3.3 soon perhaps

**Comment by ktoso** [comment]
Uhm, so I released but it seems the artifact was there already...?
Did you release @sirthias?

In any case we have the release we needed so everyone is happy.
Let's coordinate better now that more people can / will try to release spray-json 😉

**Comment by sirthias** [comment]
Sorry, Konrad. I pushed the release this morning as it was a (semi-) dependency of the parboiled2 cross-build for 2.12.0-RC2 that I actually wanted to do.

**Comment by ktoso** [comment]
I see :-)
Cool, no problem - let's coordinate next time someone jumps on releasing so we don't duplicate work :)

**Comment by sirthias** [comment]
No prob. What coordination process would you prefer?

**Comment by ktoso** [comment]
Ping on gitter or as issue here? Anything that works for you really :)
Opening tickets is likely most trackable.

**Comment by sirthias** [comment]
Ok, will do.

**Comment by ktoso** [comment]
Thanks! 👍

**Comment by fommil** [comment]
thanks! I'll do spray-json-shapeless this weekend

**Comment by ktoso** [comment]
Cool, thanks Sam :)
