### ISSUE TITLE
Scala.js cross-build

### ISSUE THREAD

**Issue by l15k4** [spray/spray-json#202]
Hey,

I'm wondering, are there any known limitations that would prevent spray-json to be compiled with scala.js? Are you planning to do so? 

My understanding is that it should be possible as spray-json doesn't depend on parboiled anymore, right?

**Comment by ktoso** [comment]
Does it make sense to cross build directly though?
Would one not rather invoke the JS native JSON.parse and pick values from it?

**Comment by l15k4** [comment]
It depends on Model complexity. I have a lot of custom JsonFormats thus I'm pretty much vendor locked to spray-json... Mostly because I'm using general types (traits) a lot. Imho `JSON.parse` would suffice only if one doesn't depend on custom JsonFormats.

**Comment by ktoso** [comment]
I mean, there's two steps here. One is `String => JsValue` and then `JsValue => Anything`, the first we don't need from spray-json if we're in a javascript environment, the second one we would need to make work (perhaps it does?)

**Comment by julienrf** [comment]
@ktoso One reason to desire a Scala.js version of spray-json would be to share the (un)marshallers between client and server implementations (so that they are consistent). I guess that’s why circe, argonaut and play-json support Scala.js.

**Comment by jrudolph** [comment]
Will be provided in the next version thanks to @jodersky's efforts in #252.
