### ISSUE TITLE
Problem with emoji?

### ISSUE THREAD

**Issue by troypayne** [spray/spray-json#207]
I'm using "com.typesafe.akka" %% "akka-http-spray-json-experimental" % "2.4.7", and doing something like:

case class User(username: String)
val userFormat = jsonFormat1(User)

and whenever username: String has an emoji in it, it does not properly handle it. I get the question mark in a bounding box.

This is something new as I just recently upgraded to scala 2.11.8, sbt 0.13.13, and replaced spray.io with akka-http, where things were being handled properly.

Has anyone seen this and know what to do?

I've confirmed that the marshaller is the problem, as I wrote a custom marshaller and the problem goes away.

**Comment by ktoso** [comment]
would you be able to prepare a reproducer (or maybe add a test for it in spray-json)? thanks in advance

**Comment by ktoso** [comment]
what's the spray-json version you were using and are using now?

**Comment by troypayne** [comment]
@ktoso 
I was using:
"io.spray" %%  "spray-json" % "1.2.6",

I'm no longer using io.spray for spray-json, but using this now along with akka-http:
"com.typesafe.akka" %% "akka-http-spray-json-experimental" % "2.4.7"

**Comment by troypayne** [comment]
@ktoso here is a reproducer

https://www.dropbox.com/s/46fy46uojcnjs1u/echo.zip?dl=0

Just download the folder, cd into echo, type: sbt run and then open another terminal on the same machine echo is running and type:

curl -XPOST 'localhost:8080/echo' -d '{"msg":"😎"}' --header "Content-Type: application/json"

You will get something back like:

{"
  "msg": "�"
}

Thanks!

**Comment by sorenbs** [comment]
I came here to look for a solution to this exact issue.

@ktso let me know if I can be of help identifying the issue.

**Comment by ktoso** [comment]
Getting a PR showing the issue is the best next step.

**Comment by troypayne** [comment]
@ktoso the project I sent isn't sufficient?

**Comment by ktoso** [comment]
I guess it may, but currently I'm so overloaded with maintaining Akka itself that did not have a chance to go over, unpack, try out etc... Any help with this is very appreciated - it's all open source after all, thanks!

**Comment by troypayne** [comment]
@ktoso ok gotcha. Can you point me in the right direction and I'll try to pinpoint the problem, fix and submit a PR? What file and maybe even function should I look at? I've attempted to find exactly where the  jsonFormatN functions are but it wasn't exactly straight forward for me at least

**Comment by ktoso** [comment]
We're in the same boat really, I did not author any parts of spray-json :)
If @sirthias would have time to look at it that would be great, but otherwise it falls to myself and the Akka team to attempt helping out here as much as we can.

First step I'd take is make your reproducer a test, like the ones here https://github.com/spray/spray-json/blob/master/src/test/scala/spray/json/BasicFormatsSpec.scala and then debug and see where the information could be lost. I'd also check if the char code itself is perhaps valid but printing in your terminal perhaps failed etc.

Thanks a lot for your help.

**Comment by troypayne** [comment]
@ktoso after attempting to create a test from my forked spray-json, all is well. I think the problem lies solely within akka-http-spray-json-experimental module. So I'm moving this issue over there to see if anyone else has had this issue: https://github.com/akka/akka-http/issues/564

**Comment by ktoso** [comment]
Interesting, good find!
Thanks.
