### ISSUE TITLE
Version 1.3.2 for Scala 2.12 is different from the one for Scala 2.11 and 2.10

### ISSUE THREAD

**Issue by jonas** [spray/spray-json#213]
As noted in https://github.com/akka/akka-http/issues/691#issuecomment-269276989 the  difference in feature set (especially 0c9b2feed5d5d253181a49beb1e806ba9df3bd1b) between v1.3.2 and v1.3.2-2.12 is causing confusion for users of Spray-JSON such as Akka HTTP. If possible please release a new version to have feature parity across all cross built Scala versions.

/cc @troypayne

**Comment by ktoso** [comment]
Was this fixed by @jrudolph recently?

**Comment by jrudolph** [comment]
Yes, good point. Released v1.3.3 last week which brings all artifacts to the same state.

**Comment by jonas** [comment]
Yes, this is fixed with the release of 1.3.3.

Refs pending upgrade done in akka/akka-http#699
