### ISSUE TITLE
Clean compilation warnings

### ISSUE THREAD

**Issue by ackratos** [spray/spray-json#215]
We have 47 compile warning in spray json about ClassManifest is deprecated and 1 warning in test about Unit inference is deprecated.

I want clean them to enhance the code quality without impact the functionality.

I am doing this because I want customize spray-json in my own project to support syntax extension.
Unfortunately, my project is compiled with -Xfatal-warning scala compiler option and I don't want violates this limitation to make my project vulnerable to compile warnings.

So could you please review/merge my PR make the spray-json free of compilation warning? Thank you very much!

**Comment by ktoso** [comment]
That specific change changes signatures and therefore breaks binary compat.
Seems we would need a new major release of it.

**Comment by jrudolph** [comment]
Fixed by #219.
