### ISSUE TITLE
JsonFormats for recursive Types, example does not compile

### ISSUE THREAD

**Issue by dr-jerry** [spray/spray-json#229]
Trying to parse a recursive Json to a recursive case class, merely following the example in https://github.com/spray/spray-json/blob/master/README.markdown.

copying and pasting the `Foo case class` and `  implicit val fooFormat: JsonFormat[Foo] = lazyFormat(jsonFormat(Foo, "i", "foo"))`

and using it to parse a body entity:
```
    path("store") {
        post {
          entity(as[Foo]]) { f =>
            println(f.i)
            complete("f.i")
          }
        }

```
gives a compile error: `could not find implicit value for parameter um: akka.http.scaladsl.unmarshalling.FromRequestUnmarshaller[nl.listop.http.Foo]`

If make it accept a List like: `entity(as[List[Foo]])` it compiles and functions well.

**Comment by stewSquared** [comment]
`as[T]` needs a `RootJsonFormat`, since it's parsing top-level json from the request.
As per the README, lazyFormat returns a regular `JsonFormat`:

> Note, that `lazyFormat` returns a `JsonFormat` even if it was given a `RootJsonFormat` which means it isn't picked up by `SprayJsonSupport`. To get back a `RootJsonFormat` just wrap the complete `lazyFormat` call with another call to `rootFormat`.

In your code, replace `implicit val fooFormat` definition with:
```scala
implicit val fooFormat: RootJsonFormat[Foo] =
  rootFormat(lazyFormat(jsonFormat(Foo, "i", "foo")))
```

**Comment by dr-jerry** [comment]
Sorry, a "RTFM". Thanks for your answer and time!
