### ISSUE TITLE
Support other letter-cases (i.e. snake_case, or kebab-case)

### ISSUE THREAD

**Issue by patrox** [spray/spray-json#234]
I have a (simplified) case class representing user information (in a 3rd party system) like this:

```scala
case class UserInfo(userId: Int, firstName: String, lastName: String)
```

But the 3rd party system responds in a JSON formatted like this:

```js
{
    "user-id": 1,
    "first-name": "John",
    "last-name": "Doe"
}
```

So, in order to deserialize the fields, I had to write my own `JsonProtocol`, just for the sake of handling `kebab-cased` field names, as the default seems to be `camelCase`.

https://en.wikipedia.org/wiki/Letter_case#Special_case_styles

Is there are better (shorter) way of doing it ?

```scala
object UserInfoProtocol extends DefaultJsonProtocol {

  implicit object UserInfoJsonFormat extends RootJsonFormat[UserInfo] {
    def write(p: UserInfo) = JsObject(
      "user-id" -> JsNumber(p.userId),
      "first-name" -> JsString(p.firstName),
      "last-name" -> JsString(p.lastName)
    )

    def read(value: JsValue) = {
      value.asJsObject.getFields(
        "user-id",
        "first-name",
        "last-name"
      ) match {
        case Seq(JsNumber(userId), JsString(firstName), JsString(lastName)) =>
          new UserInfo(userId.intValue(), firstName, lastName)
        case _ =>
          throw new DeserializationException("UserInfo expected")
      }
    }
  }
}
```

If there is no other way, do you think it would be reasonable to give users an option to override the default expectation of camelCased fields ?

**Comment by ktoso** [comment]
We're not actively developing spray-json so unless you want to contribute this feature, it is unlikely to happen.

Feel free to use any of the alternatives https://github.com/hseeberger/akka-http-json which allow such customisation.

**Comment by patrox** [comment]
thanks @ktoso for lightning-fast response :)

I'll have a look to `akka-http-json` then, as I don't mind switching to other library, if it provides what I need out-of-box.

**Comment by patrox** [comment]
by connecting the dots, I found `jackson-module-scala` whose java version I'm using on a daily basis,
so then a small fragment of boilerplate code lead me to:

```scala
object JsonUtil {
  val mapper = new ObjectMapper() with ScalaObjectMapper
  mapper.registerModule(DefaultScalaModule)
  mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
  mapper.setPropertyNamingStrategy(PropertyNamingStrategy.KEBAB_CASE)

  def toJson(value: Any): String = {
    mapper.writeValueAsString(value)
  }

  def fromJson[T](json: String)(implicit m: Manifest[T]): T = {
    mapper.readValue[T](json)
  }
}
```

But, after that the deserialization became dead simple:

```scala
val userInfo = JsonUtil.fromJson[UserInfo](body)
```

where `UserInfo` is just a plain old `case class`

**Comment by patrox** [comment]
... and since I'm too lazy to work on sth which is available from another module, I'll close this issue.
