### ISSUE TITLE
Release for 2.13.0-M5

### ISSUE THREAD

**Issue by jrudolph** [spray/spray-json#273]

**Comment by xuwei-k** [comment]
https://github.com/spray/spray-json/pull/275

**Comment by jrudolph** [comment]
I released a 2.13.0-M5 version from https://github.com/spray/spray-json/tree/v1.3.4-2.13.0-M5. It should turn up on maven central in a while.

Fixed by #275.

**Comment by SethTisue** [comment]
scala/make-release-notes@3e1d579c207f18318202ab86337d52d24eaab6de
