### ISSUE TITLE
Publish for Scala 2.13.0

### ISSUE THREAD

**Issue by godenji** [spray/spray-json#300]

**Comment by plokhotnyuk** [comment]
It is already available on the Maven Central: http://repo1.maven.org/maven2/io/spray/spray-json_2.13/

**Comment by godenji** [comment]
@plokhotnyuk great, thanks.

**Comment by raboof** [comment]
Yes, it's on Maven Central for 1.3.5, and there's PR #299 to make sure it's automatic for subsequent releases
