### ISSUE TITLE
Provide jsonFormatN method overloads

### ISSUE THREAD

**Issue by jrudolph** [spray/spray-json#310]
That's instead of the numbered generated `jsonFormat1`, `jsonFormat2`, etc. because those will be much easier to use if you want to add or remove fields.

Not sure why this wasn't done like this from the beginning. Maybe overloading was improved since back then?

**Comment by sirthias** [comment]
There was a reason back then, which caused problems with the overloads.
Maybe some post-erasure method signature collision?
I don't remember.

Let's see if there are issues creeping up now...

**Comment by jrudolph** [comment]
> There was a reason back then, which caused problems with the overloads.
> Maybe some post-erasure method signature collision?
> I don't remember.

See #311, maybe it was the issue that you always have to write `jsonFormatN(X.apply _)` instead of `jsonFormat13(X)` which works if `X` has no companion object.

**Comment by sirthias** [comment]
Yeah, that might have been it.

**Comment by jrudolph** [comment]
Done in #311.
