### ISSUE TITLE
What are your plans for spray-json regarding Scala 3?

### ISSUE THREAD

**Issue by informarte** [spray/spray-json#339]

**Comment by raboof** [comment]
a quick attempt (https://github.com/raboof/spray-json-on-scala3) suggests the current 2.13 artifacts seem to work OK on Scala 3 - are you aware of any limitations?

**Comment by informarte** [comment]
mill dependency: `ivy"io.spray::spray-json:1.3.5".withDottyCompat(scalaVersion())`

**Comment by paoloboni** [comment]
not strictly related to the plans for spray-json on Scala 3 - but in case you want to use it on Scala 3, the library [spray-json-derived-codecs](https://github.com/paoloboni/spray-json-derived-codecs) allows you to derive `JsonFormat`s using Scala 3 type class derivation

**Comment by informarte** [comment]
Thanks everyone for answers and pointers!
