### ISSUE TITLE
Sealed traits

### ISSUE THREAD

**Issue by fommil** [spray/spray-json#42]
if I have a sealed trait

``` scala
sealed trait Failure
```

and if I have a bunch of implementations, all case classes, is there a nice way to support marshalling and unmarshalling? I ended up writing one hell of a hack and it occurs to me you might have an elegant solution (my hack involves switching on the class type and inserting the classname into the JSON, then switching on the class name from the JSON and using hard-coded clasasnames to then switch to get the right unmarshaller)

**Comment by dskrvk** [comment]
Proposed implementation: #186
