### ISSUE TITLE
Support default parameters

### ISSUE THREAD

**Issue by stanch** [spray/spray-json#55]
I am not sure if it’s possible, but would be great if spray-json supported case classes with some of the parameters having default values. What I mean is if we have

```
case class Test(a: Int = 3, b: Int)
```

then

```
{"b": 4}
```

should deserialize into

```
Test(3, 4)
```

instead of failing.

**Comment by klpx** [comment]
Hi! Seems like spray-json2 is not planned. How about this feature?
