### ISSUE TITLE
Jackson convertor

### ISSUE THREAD

**Issue by fommil** [spray/spray-json#69]
It would be fantastic if there were a convertor to go between Spray JSON's `JsValue` and Jackson's `JsonNode`. That way, Spray JSON could be more efficiently leveraged in traditional containers (with [json2xml](https://github.com/lukas-krecan/json2xml) a one-way bridge to JAXB). Currently, in order to use Spray JSON in traditional containers requires marshalling to/from `String`

**Comment by fommil** [comment]
oh damn, I wrote one of these at my last gig and never OSSd it when I had the chance. Bugger!

**Comment by trams** [comment]
I am very interested in this task. Would you consider merging it if I implement it? Or is there cleaner way to make jackson <--> spray interop?

A bit of context. I want to wrap MLeap library as a Finatra web service. Finatra is built with jackson support by default and I want to stick to it but MLeap object could be easily serialised only to JsValue tree. So I thought about writing a JsNode (jackson) <--> JsValue (spray) bridge. I am not sure I could convert all objects given that jackson has some weird nodes like POJO, Binary and Missing. But even partial marshaling should be fine given that in most cases one would not encounter these node.

What do you think?
