### ISSUE TITLE
serialization roundtrip for Option[Option[T]]

### ISSUE THREAD

**Issue by ritschwumm** [spray/spray-json#7]
Some(None) becomes null, and null becomes None, right?

**Comment by ritschwumm** [comment]
@jrudolph just saw your commit referenced above.
looks like we had the same idea how to solve this in an elegant way :)

**Comment by ritschwumm** [comment]
is this fixed now?

**Comment by ktoso** [comment]
There seems to have been a commit 4 years ago by @jrudolph but did not close ticket... ;-)
I think it'd be most useful if you'd try it out and report back if we can close it @ritschwumm - thanks.

**Comment by ritschwumm** [comment]
i  probably won't try it out - too much other stuff to do, sorry.

**Comment by ktoso** [comment]
Help us, help you 😉  Since you pinged the ticket I expected you have interest in this feature?
Would be just as simple as upgrading the dependency and trying in a test 😄

**Comment by ritschwumm** [comment]
nah, i just want the ticket closed - i don't even use spray-json...
